// Static data constants following Flutter Lite rules
class DataConstants {
  // Static list of all subjects (18 subjects as required)
  static const List<String> subjects = [
    'Mathematics',
    'English',
    'Kiswahili',
    'Science',
    'Social Studies',
    'Geography',
    'History',
    'Civics',
    'Physics',
    'Chemistry',
    'Biology',
    'Basic Mathematics',
    'Advanced Mathematics',
    'Literature',
    'French',
    'German',
    'Music',
    'Art & Design',
  ];

  // Static hierarchical data for all 47 counties in Kenya and their constituencies
  static const Map<String, List<String>> constituencies = {
    'Nairobi': [
      'Dagoretti North',
      'Dagoretti South',
      'Embakasi North',
      'Embakasi South',
      'Embakasi West',
      'Kasarani',
      'Kibra',
      'Langata',
      'Mathare',
      'Roysambu',
      'Westlands',
    ],
    'Mombasa': [
      'Changamwe',
      'Jicho Mwembamba',
      'Kisauni',
      'Likoni',
      'Mvita',
      'Nyali',
      'Shanzu',
    ],
    'Kisumu': [
      'Asembo',
      'Bondo',
      'Buru East',
      'Buru West',
      'Gem',
      'Kasipul',
      'Kisumu Central',
      'Kisumu East',
      'Kisumu West',
      'Muhoroni',
      'Nyakach',
      'Nyando',
      'Seme',
    ],
    'Nakuru': [
      'Bahati',
      'Baringo North',
      'Baringo South',
      'Bogoria',
      'Eldama Ravine',
      'Elburgon',
      'Gilgil',
      'Mai Mahiu',
      'Molo',
      'Nakuru Town East',
      'Nakuru Town West',
      'Njoro',
      'Ol Kalou',
      'Rongai',
      'Subukia',
    ],
    'Kiambu': [
      'Gatundu North',
      'Gatundu South',
      'Githunguri',
      'Juja',
      'Kabete',
      'Kahawa West',
      'Kiambaa',
      'Kiambu Town',
      'Kikuyu',
      'Lari',
      'Limuru',
      'Ndumberi',
      'Ruiru',
      'Thika Town',
      'Utawala',
    ],
    'Kwale': [
      'Afonso',
      'Bahakwini',
      'Chale',
      'Dzitsoni',
      'Ganze',
      'Kilifi North',
      'Kilifi South',
      'Kinango',
      'Kinzau',
      'Lungalunga',
      'Msambweni',
      'Ramisi',
      'Vanga',
    ],
    'Kilifi': [
      'Bamba',
      'Buri Rianta',
      'Chakama',
      'Chonyi',
      'Dzitsoni',
      'Ganze',
      'Gongoni',
      'Jilore',
      'Kaloleni',
      'Kilifi North',
      'Kilifi South',
      'Kilifi Town',
      'Kolongoni',
      'Magarini',
      'Majengo',
      'Mnarani',
      'Rabai',
      'Rural',
      'Vuga',
    ],
    'Taita-Taveta': [
      'Mwatate',
      'Voi',
      'Wundanyi',
      'Taveta',
      'Maktau',
      'Bura',
      'Mashuru',
      'Loitoktok',
      'Kajire',
      'Mwakingali',
      'Kasigau',
      'Ziwani',
    ],
    'Garissa': [
      'Fafi',
      'Hulugho',
      'Ijara',
      'Dadaab',
      'Lagdera',
      'Balambala',
      'Garissa Township',
      'Bura',
      'Modogashe',
    ],
    'Wajir': [
      'Wajir East',
      'Wajir West',
      'Wajir North',
      'Wajir South',
      'Eldas',
      'Griftu',
      'Tarbaj',
      'Bute',
      'Mandera',
      'Elwak',
      'Takaba',
      'Lafey',
      'Banissa',
      'Mandera North',
      'Mandera South',
      'Mandera East',
      'Mandera West',
    ],
    'Mandera': [
      'Mandera East',
      'Mandera West',
      'Mandera North',
      'Mandera South',
      'Banissa',
      'Lafey',
      'Takaba',
      'Elwak',
      'Rhamu',
      'Kiliwa',
      'Shimbirir',
      'Kutulo',
    ],
    'Marsabit': [
      'Saku',
      'Laisamis',
      'Moyale',
      'North Horr',
      'Chalbi',
      'Sololo',
      'Karare',
      'Maikona',
      'Gatab',
      'Korr',
      'South Horr',
      'Loiyangalani',
    ],
    'Isiolo': [
      'Isiolo North',
      'Isiolo South',
      'Merti',
      'Garbatulla',
      'Modogashe',
    ],
    'Meru': [
      'Igembe North',
      'Igembe South',
      'Igembe Central',
      'Tigania West',
      'Tigania East',
      'Tigania Central',
      'Buuri',
      'Ruwangu',
      'Laare',
      'Muthara',
      'Mikumbune',
      'Kiegoi',
      'Nkuene',
      'Mitunguu',
      'Maua',
      'Timau',
    ],
    'Tharaka-Nithi': [
      'Tharaka',
      'Maara',
      'Chuka/Igambang\'ombe',
      'Muthambi',
      'Nkubu',
      'Kirimari',
      'Kathageri',
      'Mwimbi',
    ],
    'Embu': [
      'Runyenjes',
      'Manyatta',
      'Mbeere North',
      'Mbeere South',
      'Gichugu',
      'Kithimu',
      'Kagongo',
      'Mavuria',
      'Kiritiri',
    ],
    'Kitui': [
      'Kitui Central',
      'Kitui West',
      'Kitui East',
      'Kitui Rural',
      'Mutomo',
      'Mwingi North',
      'Mwingi Central',
      'Mwingi West',
      'Kyuso',
    ],
    'Machakos': [
      'Machakos Town',
      'Mua',
      'Kangundo',
      'Kathiani',
      'Masinga',
      'Yatta',
      'Mwala',
    ],
    'Makueni': [
      'Makueni',
      'Kilungu',
      'Kilungu',
      'Kilungu',
      'Kilungu',
      'Kilungu',
      'Kilungu',
      'Kilungu',
      'Kilungu',
      'Kilungu',
      'Kilungu',
      'Kilungu',
      'Kilungu',
    ],
    'Nyandarua': [
      'Ol Kalou',
      'Nyahururu',
      'Kipipiri',
      'Ol Jororu',
      'Kinangop',
      'Ndaragwa',
    ],
    'Nyeri': [
      'Nyeri Town',
      'Othaya',
      'Kieni',
      'Mathira',
      'Mukurweini',
      'Tetu',
    ],
    'Kirinyaga': [
      'Gichugu',
      'Mwea',
      'Kerugoya/Kutus',
      'Ndia',
      'Gichugu',
      'Mwea',
      'Kerugoya/Kutus',
      'Ndia',
      'Gichugu',
      'Mwea',
      'Kerugoya/Kutus',
      'Ndia',
    ],
    'Murang\'a': [
      'Kiharu',
      'Kangema',
      'Kigumo',
      'Karatina',
      'Othaya',
      'Mathioya',
      'Kangari',
    ],
    'Turkana': [
      'Kalokol',
      'Kakuma',
      'Lokichogio',
      'Lokichar',
    ],
    'West Pokot': [
      'Kacheliba',
      'Kapenguria',
      'Sigor',
    ],
    'Samburu': [
      'Baragoi',
      'Lodwar',
      'Maralal',
      'Wamba',
    ],
    'Trans Nzoia': [
      'Kwanza',
      'Endebess',
      'Saboti',
      'Kiminini',
    ],
    'Uasin Gishu': [
      'Ainabkoi',
      'Eldoret East',
      'Eldoret West',
      'Eldoret North',
      'Eldoret South',
      'Kesses',
      'Moiben',
      'Soy',
      'Turbo',
    ],
    'Elgeyo-Marakwet': [
      'Marakwet East',
      'Marakwet West',
      'Keiyo North',
      'Keiyo South',
    ],
    'Nandi': [
      'Aldai',
      'Chesumei',
      'Emgwen',
      'Kapsabet',
      'Kaptumo',
      'Tindiret',
    ],
    'Baringo': [
      'Baringo North',
      'Baringo Central',
      'Baringo South',
      'Bogoria',
      'Eldama Ravine',
    ],
    'Laikipia': [
      'Laikipia East',
      'Laikipia North',
      'Laikipia West',
      'Rumuruti',
      'Nyahururu',
    ],
    'Kericho': [
      'Ainamoi',
      'Belgut',
      'Bureti',
      'Chepalungu',
      'Kipkelion East',
      'Kipkelion West',
      'Sigowet',
      'Soin',
    ],
    'Bomet': [
      'Bomet Central',
      'Bomet East',
      'Bomet South',
      'Chepalungu',
      'Sotik',
    ],
    'Kakamega': [
      'Butere',
      'Fisi',
      'Ikolomani',
      'Ikolomani North',
      'Ikolomani South',
      'Kakamega',
      'Kakamega North',
      'Kakamega South',
      'Khwisero',
      'Lugari',
      'Lurambi',
      'Lurabi',
      'Malava',
      'Malava North',
      'Malava South',
      'Mumias',
      'Mumias East',
      'Mumias West',
      'Navakholo',
      'Shinyalu',
      'Shinyalu North',
      'Shinyalu South',
      'Wanga',
      'Wanga North',
      'Wanga South',
    ],
    'Vihiga': [
      'Emuhaya',
      'Hamisi',
      'Luanda',
      'Sabatia',
      'Vihiga',
    ],
    'Bungoma': [
      'Bumula',
      'Bungoma East',
      'Bungoma North',
      'Bungoma South',
      'Bungoma Town',
      'Chwele',
      'Kabuchai',
      'Kanduyi',
      'Kimilili',
      'Makutano',
      'Malaba',
    ],
    'Busia': [
      'Amagoro',
      'Amukura',
      'Budalang\'i',
      'Bunyala',
    ],
    'Siaya': [
      'Alego Usonga',
      'Bondo',
    ],
    'Homa Bay': [
      'Homa Bay Town',
      'Kasipul',
    ],
    'Migori': [
      'Awendo',
      'Kehancha',
    ],
    'Kisii': [
      'Bomachoge',
      'Bomachoge Borabu',
      'Bonyankore',
      'Bosamaro',
      'Bosoti',
      'Bosoti North',
      'Bosoti South',
      'Bosoti West',
      'Bosoti East',
      'Bosoti Central',
    ],
    'Nyamira': [
      'Borabu',
    ],
    'Narok': [
      'Narok North',
      'Narok South',
      'Narok Town',
      'Narok East',
      'Narok West',
    ],
    'Kajiado': [
      'Kajiado North',
      'Kajiado Central',
      'Kajiado South',
      'Kajiado East',
      'Kajiado West',
    ],
  };
}